name = "awesome-shadcn-ui"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "awesome-shadcn-ui"

[images]
binding = "IMAGES"

[build]
command = "pnpm run build && pnpm exec opennextjs-cloudflare build"

[build.environment]
NEXTJS_ENV = "production"
